export const GET_FOR_USER = 'getPublicationsForUsers'
export const LOADING = 'loadingPublications'
export const ERROR = 'errorPublications'
export const COM_LOADING = 'comLoading'
export const COM_ERROR = 'comError'
export const COM_UPDATE = 'comUpdate'